[package]
name = "epochgrid-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
async-nats.workspace = true
nkeys.workspace = true
openmls.workspace = true
openmls_basic_credential.workspace = true
openmls_rust_crypto.workspace = true
openmls_sqlite_storage.workspace = true
openmls_traits.workspace = true
postcard.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

zeroize.workspace = true

[dev-dependencies]
tempfile = "3"
